### ISSUE TITLE
Rownames of rz in pearsonCor function gives me an error in dimnames

### ISSUE THREAD

**Issue by Hannibal83dk** [cran/ctrlGene#1]
> test <- pearsonCor(expression, ctVal)
Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent

I have narrowed it to the
rowname_rz = c(rowname_rz, colnames(expression[i + 1]), "p-value")

I suggest moving an ending parenthesis:
rowname_rz = c(rowname_rz, colnames(expression)[i + 1], "p-value")

full function:
pearsonCor <- function (expression, ctVal = TRUE) 
{
  if (!ctVal) {
    expression = log2(expression)
  }
  n = ncol(expression)
  rz = matrix(ncol = n, nrow = 2 * (n - 1))
  colnames(rz) = colnames(expression)
  rowname_rz = list()
  for (i in 1:n) {
    for (j in 2:n) {
      COT_TEST = cor.test(expression[, i], expression[, 
                                                      j])
      rz[2 * (j - 1) - 1, i] = COT_TEST$estimate
      rz[2 * (j - 1), i] = COT_TEST$p.value
    }
    if (i + 1 > n) 
      break
    rowname_rz = c(rowname_rz, colnames(expression)[i + 1], 
                   "p-value")
  }
  rownames(rz) = unlist(rowname_rz)
  return(round(rz, 3))
}

Kind Regards
Patrick

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by Hannibal83dk** [comment]
Ok thanks!
